### PR TITLE
[T2A4][F10-A1]Tan Boon Joon

### PR DESCRIPTION
**Pull request by tanboonjoon**
remove SLAP on main method

inline methods in executeCommand method

lack of abstraction in executeEditPersonProperties method

### CODE REVIEW

**Comment by tanboonjoon** [comment]
ready for review

**Comment by jeffryhartanto** [comment]
Please change the title according to my comment in #507. Make sure you use the correct title next time..

**Comment by tanboonjoon** [comment]
change part of the title from A01 to A1
ready for review

**Comment by Candiie** [comment]
Good Effort for trying! Though it can be even smellier :)

**Pull request closed without merging**
