### PR TITLE
[T2A5][A1]Hong Wei

### PR DESCRIPTION
**Pull request by imhongw**
Ready for review.

### CODE REVIEW

**Comment by jeffryhartanto** [comment]
Please mention which tutorial are you in before team id, e.g. [T09-A1].. Make sure you use the correct title next time..

**Comment by imhongw** [comment]
Hi Jeffry,

I’m terribly sorry about that. Will not repeat again.

Thanks and regards,
Hong Wei
On 27 Aug 2016, at 18:56, Jeffry Hartanto <notifications@github.com<mailto:notifications@github.com>> wrote:

Please mention which tutorial are you in before team id, e.g. [T09-A1].. Make sure you use the correct title next time..

**Comment by mauris** [comment]
@imhongw please also edit your title so that your tutor can come and comment on your code.

**Comment by imhongw** [comment]
Dear Sam,

Title as in profile name?

Regards,
Hong Wei
On 27 Aug 2016, at 22:05, Sam-Mauris Yong <notifications@github.com<mailto:notifications@github.com>> wrote:

@imhongwhttps://github.com/imhongw please also edit your title so that your tutor can come and comment on your code.

**Comment by jeffryhartanto** [comment]
@imhongw Your PR title is still incorrect. You haven't mentioned your tutorial group. Should be [T2A5][T09-A1]Hong Wei if your tutorial is on Thursday 9AM.

**Comment by imhongw** [comment]
Dear Jeffry,

I have done the needed amendments. Sorry for the inconvenience.

Regards,
Hong Wei

On 27 Aug 2016, at 22:11, Jeffry Hartanto <notifications@github.com<mailto:notifications@github.com>> wrote:

[T2A5][T09-A1]Hong Wei

**Pull request closed without merging**
