### PR TITLE
[T2A3][F10-A1]Tan Boon Joon

### PR DESCRIPTION
**Pull request by tanboonjoon**
remove SLAP on main methods

### CODE REVIEW

**Comment by tanboonjoon** [comment]
ready for review

**Comment by jeffryhartanto** [comment]
Please change part of the title from A01 to A1. Make sure you use the correct title next time

**Comment by tanboonjoon** [comment]
change part of the title from A01 to A1
ready for review

**Comment by Candiie** [comment]
Hi @tanboonjoon as mentioned in #509 do provide 1 commit per change instead of lumping it together for your (Decrease SLAP n Smelliest Code) similarly, instead of "edited code" you can simply comment it Decreasing SLAP :) otherwise well done decreasing SLAP ~

**Pull request closed without merging**
