### PR TITLE
[T2A2][W13-A1]Yong Zhi Yuan

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Ready for review

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
Ready for review

**Comment by okkhoy** [comment]
@Zhiyuan-Amos  why have you closed this yourself? :-/

**Comment by okkhoy** [comment]
- nitpick: `processUserInput()`  can you think of a different name?
- take care of indentation! set Eclipse indentation to 4 spaces and not tabs.
- if you add a method to refactor the code, you need to ensure that you add appropriate header comments, write new tests to check if this method works as expected/code works as expected with the change etc., also if applicable, update user guide/help (cf. `createFile()`)
- `setupForExit()` is not doing anything useful and your intent is also not documented in the form of header comments.
- in general, pay more attention to coding standards violation.
- some useful ones include checking how conditional statements are written, naming conventions etc.,

**Comment by okkhoy** [comment]
@Zhiyuan-Amos  btw, you need to rename the PR in the correct format.

**Comment by Zhiyuan-Amos** [comment]
Hello! Thank you for your review :)

I have closed this on my own as I was thinking of redo-ing it, since you mentioned in class that I should correct some of these mistakes first. Also, I have renamed the PR in the correct format.

nitpick: processUserInput() can you think of a different name?
Response: is processUserInputUntilExit() a better name? Since the program only exits when the user inputs the keyword 'exit'.

take care of indentation! set Eclipse indentation to 4 spaces and not tabs.
Response: Yes! I have changed the settings on Eclipse.

if you add a method to refactor the code, you need to ensure that you add appropriate header comments, write new tests to check if this method works as expected/code works as expected with the change etc., also if applicable, update user guide/help (cf. createFile())
setupForExit() is not doing anything useful and your intent is also not documented in the form of header comments.
Response: Noted! Yes, to be honest, it was pretty boring to add in comments for every single new refactoring, that's why I omitted them totally. But I get the point of the exercise and have learnt my lesson, thank you! :)

in general, pay more attention to coding standards violation.
some useful ones include checking how conditional statements are written, naming conventions etc.,
Response: I have noted that there are magic numbers in the code. However I wasn't able to spot other coding standards violation T.T Do you have any hints on which part of the code are there such errors?

Thanks much Akshay!

**Pull request closed without merging**
