### PR TITLE
[T2A5][F10-A1]Tan Boon Joon

### PR DESCRIPTION
**Pull request by tanboonjoon**
make find method case-insensitive
add executeSortAddressbook method
add executeEditPersonProperties method

### CODE REVIEW

**Comment by tanboonjoon** [comment]
ready for review

**Comment by jeffryhartanto** [comment]
Please change the title according to my comment in #507. Make sure you use the correct title next time..

**Comment by tanboonjoon** [comment]
change part of the title from A01 to A1
ready for review

**Comment by Candiie** [comment]
Hi @tanboonjoon as mentioned during the tutorial, do provide 1 commit per significant change and do include a summarized comment of what changes had been done instead of commenting on the pull request itself. For e.g. in the future, "make find method case-insensitive", "add executeSortAddressbook method" and " add executeEditPersonProperties method" could be the comment of your commits. 

Otherwise well done and well explained for your case-insensitive implementation as you've discussed and shown during the tutorial.

**Pull request closed without merging**
