### PR TITLE
[T2A3][T09-A4]Zhang Yunxuan

### PR DESCRIPTION
**Pull request by yunxz**

### CODE REVIEW

**Comment by yunxz** [comment]
inline method processProgramArgs()

**Comment by mauris** [comment]
@yunxz is this PR ready for review? (:

**Comment by yunxz** [comment]
Yep :)

**Comment by mauris** [comment]
alright, as mentioned in tutorial, your change does show how SLAP is decreased. I see that you have a few revert commits. If you have time, try looking up on the command `git revert head~1`. Google and see how the `~1` works.

**Pull request closed without merging**
