### PR TITLE
[T2A2][T15-A1] Leow Zheng Yu

### PR DESCRIPTION
**Pull request by zhengyu92**
Ready for Review

### CODE REVIEW

**Comment by jeffryhartanto** [comment]
Please change the title according to my comment in #441. Make sure you use the correct title next time.

**Comment by zhengyu92** [comment]
Hi, I see my title as [T2A2][T15A1] Leow Zheng Yu already. Can I know where is the wrong title please?

**Comment by jeffryhartanto** [comment]
@zhengyu92 it should be [T2A2][T15-A1].

**Comment by K1ang** [comment]
@zhengyu92 
- Good job in improving SLAP for the main method to improve code quality.
- However there are more ways that could be explored too (eg. common refactorings that were covered in class). Do give them a try when you have time.
- A reminder for the tab issues with Eclipse. 
- Good to commit each time for each distinct change (for this time is each refactoring).

**Pull request closed without merging**
